name: iris
functions:
- url: ./src/iris.yaml
  name: xgb
- url: https://raw.githubusercontent.com/mlrun/mlrun/master/examples/xgb_serving.ipynb
  name: serving
workflows:
- name: main
  path: src/workflow.py
